/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as genericErc20MockSolSol from "./GenericERC20Mock.sol.sol";
export { FundMockAggregator__factory } from "./FundMockAggregator__factory";
