/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as genericErc20MockSolSol from "./GenericERC20Mock.sol.sol";
export type { genericErc20MockSolSol };
export type { FundMockAggregator } from "./FundMockAggregator";
